Homework #2
YuMichay/react-homework pull request #2
Opened 2023-11-23 17:38 UTC by YuMichay

2023-11-23 18:10 UTC, tagizade-samir requested changes

2023-11-23 18:10 UTC, tagizade-samir commented on src/helpers/handleLocale.js
> +  state.locale = e.target.textContent
Давай этот момент (контроль состояния локализации) переделаем с переменной на состояние. К примеру ты можешь поместить это состояние в корень проекта (как мы делали на уроке), либо я бы предложил поместить это прямо в твой хук useLocalization(). Таким образом твой хук будет хранить состояние локализации, а также функцию для смены языка (которую этот хук будет возвращать и ты сможешь использовать ее в любом месте проекта)

2023-11-23 18:10 UTC, tagizade-samir commented on src/screens/PublicNotes/PublicNotes.jsx
> +        {publicNotes
Тут проверка не совсем корректная. Так как твоя переменная publicNotes является массивом (метод filter возвращает массив в любом случае), и твоя проверка всегда будет true, так как массив является true-шным значением. Давай поменяем проверку на publicNotes.length

2023-11-23 20:08 UTC, YuMichay commented on src/helpers/handleLocale.js
> +  state.locale = e.target.textContent
![Снимок экрана 2023-11-23 205542](https://github.com/YuMichay/react-homework/assets/82322742/405c3852-c548-4325-a330-92cd0fca17d1)
![Снимок экрана 2023-11-23 210439](https://github.com/YuMichay/react-homework/assets/82322742/efaa3fa7-4631-4634-98c0-4e022cbd4cb1)
Как-то так?

2023-11-25 11:01 UTC, tagizade-samir approved these changes

2023-11-25 14:46 UTC, merged